aplicacao/config/routes.rb
Rails.application.routes.draw do
  resources :livros
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root 'static_pages#home'
  root to: 'livros#index'
end

aplicacao/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

aplicacao/app/models/livro.rb
class Livro < ApplicationRecord
end

aplicacao/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

aplicacao/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

aplicacao/app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: %i[ show edit update destroy ]

  # GET /livros or /livros.json
  def index
    @livros = Livro.all
  end

  # GET /livros/1 or /livros/1.json
  def show
  end

  # GET /livros/new
  def new
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
  end

  # POST /livros or /livros.json
  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to livro_url(@livro), notice: "Livro was successfully created." }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livros/1 or /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to livro_url(@livro), notice: "Livro was successfully updated." }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1 or /livros/1.json
  def destroy
    @livro.destroy

    respond_to do |format|
      format.html { redirect_to livros_url, notice: "Livro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def livro_params
      params.require(:livro).permit(:titulo, :autor, :ano, :editora, :edicao, :livro_eletronico)
    end
end

aplicacao/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

aplicacao/app/helpers/application_helper.rb
module ApplicationHelper
end

aplicacao/app/helpers/livros_helper.rb
module LivrosHelper
end

aplicacao/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

aplicacao/app/views/admin_users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

aplicacao/app/views/admin_users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

aplicacao/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biblioteca Pessoal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <div class="row">
      <div class="col">


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="<%= root_path %>">&nbsp;&nbsp;Biblioteca</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="<%= root_path %>">Início</a>
        </li>
      </ul>
      <span class="navbar-text">
      <% if current_user %>
      <%= button_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Login', new_user_session_path , :class => "btn btn-outline-primary"%>
    <% end %>
      </span>
    </div>
  </nav>

    <%= yield %>
      </div>
      </div>
    </div>
  </body>
</html>

aplicacao/app/views/livros/_form.html.erb
<%= form_with(model: livro) do |form| %>
  <% if livro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(livro.errors.count, "error") %> sem permissão para salvar:</h2>

      <ul>
        <% livro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :autor, style: "display: block" %>
    <%= form.text_field :autor, :class => "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :ano, style: "display: block" %>
    <%= form.number_field :ano, :class => "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :editora, style: "display: block" %>
    <%= form.text_field :editora, :class => "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :edicao, style: "display: block" %>
    <%= form.number_field :edicao, :class => "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :livro_eletronico, style: "display: block" %>
    <%= form.check_box :livro_eletronico %>
  </div>

  <div>
    <%= form.submit "Salvar", class: 'btn btn-success'  %>
  </div>
<% end %>

aplicacao/app/views/livros/_livro.html.erb
<div id="<%= dom_id livro %>">
  <p>
    <strong>Titulo:</strong>
    <%= livro.titulo %>
  </p>

  <p>
    <strong>Autor:</strong>
    <%= livro.autor %>
  </p>

  <p>
    <strong>Ano:</strong>
    <%= livro.ano %>
  </p>

  <p>
    <strong>Editora:</strong>
    <%= livro.editora %>
  </p>

  <p>
    <strong>Edicao:</strong>
    <%= livro.edicao %>
  </p>

  <p>
    <strong>Livro eletronico:</strong>
    <%= livro.livro_eletronico %>
  </p>

</div>

aplicacao/app/views/livros/edit.html.erb
<h1>Editando o livro</h1>

<%= render "form", livro: @livro %>

<br>

<div>
  <%= link_to "Mostrar este livro", @livro %> |
  <%= link_to "Voltar à lista de livros", livros_path %>
</div>

aplicacao/app/views/livros/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Livros</h1>

<div id="livros">
  <div class="table-responsive"> 
  <table class="table table-hover">
  <thead class="thead-light">
    <tr>
      <th>Título</th>
      <th>Autor</th>
      <th>Ano</th>
      <th>Editora</th>
      <th>Livro Eletrônico</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @livros.each do |livro| %>
      <tr>
        <td><%= livro.titulo %></td>
        <td><%= livro.autor %></td>
        <td><%= livro.ano %></td>
        <td><%= livro.editora %></td>
        <td><%= livro.livro_eletronico %></td>
        <td><%= link_to 'Mostrar', livro, :class => "btn btn-primary" %></td>
        <td><%= link_to 'Editar', edit_livro_path(livro), :class => "btn btn-secondary" %></td>
        <td><%= link_to 'Apagar', livro, method: :delete, data: { confirm: 'Tem certeza?' }, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
  </div>
</div>
<div id="adicionar">
<%= link_to "Adicionar livro", new_livro_path, :class => "btn btn-primary" %>
</div>

aplicacao/app/views/livros/new.html.erb
<h1>Novo livro</h1>
<div class="form-group">
<%= render "form", livro: @livro %>
</div>
<br>

<div>
  <%= link_to "Voltar à lista de livros", livros_path %>
</div>

aplicacao/app/views/livros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @livro %>

<div>
  <%= link_to "Editar livro", edit_livro_path(@livro) %> |
  <%= link_to "Voltar à lista de livros", livros_path %>

  <%= button_to "Excluir este livro", @livro, method: :delete %>
</div>

aplicacao/app/views/static_pages/home.html.erb
<h1>Biblioteca Pessoal</h1>

aplicacao/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

aplicacao/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>